
# Matrix landing — added by Kiro
matrix.aliterra.space {
        encode gzip zstd

        root * /var/www/matrix.aliterra.space
        file_server

        header {
                Strict-Transport-Security "max-age=31536000; includeSubDomains"
                X-Content-Type-Options "nosniff"
                Referrer-Policy "strict-origin-when-cross-origin"
                # длительный кэш статики
                Cache-Control "public, max-age=3600"
                -Server
        }
}
